### ISSUE TITLE
Ndarray shape mismatch between lf0 and lf0_score in data/data_source.py with PJS data-set on Google Colaboratory.

### ISSUE THREAD

**Issue by taroushirani** [r9y9/nnsvs#8]
When I use NNSVS with PJS corpus on Google Colaboratory, I get ValueError on stage 1 and fail to extract acoustic features.  I attempted print debug on data/data_source.py and found that the shape of lf0_score in collect_features differed before and after interp1d at line 191, so this may be the bug of nnmnkwii, not nnsvs, but I could not  find the cause any more.

I uploaded the failed ipynb to gist so please see it for detail.

  https://gist.github.com/taroushirani/a44491c94c924d38a87433fe581b2b05

**Comment by r9y9** [comment]
Thanks for the report. I had a fix for this locally but forgot to push it to the repository. The problem is that there are a few alignment mismatches between wav and musicxml files. 

https://github.com/r9y9/nnsvs/commit/cbbf315ddc69209b71331345fa0255c3b607a524 This should workaround the issue. I reported the alignment issue to one of the authors of PJS corpora. I hope they fix it in the next release (perhaps PJS 1.2?).

**Comment by taroushirani** [comment]
Thank you for your rapid response.  I confirmed the problem is solved with the latest NN-SVS.

**Comment by r9y9** [comment]
Thanks!
